### ISSUE TITLE
Conflicting license terms

### ISSUE THREAD

**Issue by unixorn** [sflems/piboy-zsh-theme#1]
I was going to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the license file and the readme have conflicting terms - the license file says MIT, but the readme says All Rights Reserved.

**Comment by sflems** [comment]
Feel free! Readme has been updated. I'll leave this open for now should you have any questions.

**Comment by sflems** [comment]
I'll also be converting it to an appropriate zsh theme. I can open up a PR when ready 👌

**Comment by sflems** [comment]
License updated, theme converted.
[See PR.](https://github.com/unixorn/awesome-zsh-plugins/pull/1378)

Cheers!

**Comment by unixorn** [comment]
Looks good, thanks
